export const CAPACITY_SAMPLES = Array(100).fill({
  arrivalDate: "2023-01-01",
  arrivalBorder: "MN",
  import: true,
  containerNumber: 21,
  capacity: 1000,
  brokerName: "Галбадрал",
  load: true,
  sell: true,
  price: 13000,
  brokerCode: 52525,
  blockNumber: 14,
  unloadedSite: true,
  arrivedSite: true,
  unloaded: true,
  released: false,
  loaded: false,
});
export const CAPACITY_COLUMNS = [
  { title: "Дөхөлт огноо", dataIndex: "arrivalDate" },
  { title: "Орох хил", dataIndex: "arrivalBorder" },
  { title: "Ирэх/Явах", dataIndex: "import" },
  { title: "Чингэлэгийн дугаар", dataIndex: "containerNumber" },
  { title: "Багтаамж", dataIndex: "capacity" },
  { title: "Зуучийн нэр", dataIndex: "brokerName" },
  { title: "Ачилт хийсэн", dataIndex: "load" },
  { title: "Борлуулалт", dataIndex: "sell" },
  { title: "Үнэ", dataIndex: "price" },
  { title: "Зуучийн код", dataIndex: "brokerCode" },
  { title: "Блокийн дугаар", dataIndex: "blockNumber" },
  { title: "Талбайд задарсан", dataIndex: "unloadedSite" },
  { title: "Талбайд ирсэн", dataIndex: "arrivedSite" },
  { title: "Задарсан", dataIndex: "unloaded" },
  { title: "Суларсан", dataIndex: "released" },
  { title: "Ачаалласан", dataIndex: "loaded" },
];
